name: AutoPix
version: 1.0.26
main: io.github.warleysr.autopix.AutoPix
author: warleysr
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  autopix:
    description: Valida uma transação realizada por PIX.
  autopixmenu:
    description: Abre o menu de produtos disponíveis para compra por PIX.
